pizza_type_name = {
    'classic': ['pepperoni', 'ham and mushrooms', 'teriyaki', 'salami', 'rancho', 'mexicana'],
    'veggie': ['four cheese', 'margarita', 'teriyaki', 'mushroom', 'jalapeno', 'rancho', 'mexicana']
}

pizza_type_name_size_price = [
    {'type': 'classic', 'name': 'pepperoni', 'size': 'S', 'price': 8},
    {'type': 'classic', 'name': 'pepperoni', 'size': 'M', 'price': 10},
    {'type': 'classic', 'name': 'pepperoni', 'size': 'L', 'price': 12},
    {'type': 'classic', 'name': 'pepperoni', 'size': 'XL', 'price': 15},
    {'type': 'classic', 'name': 'pepperoni', 'size': 'XXL', 'price': 18},
    {'type': 'classic', 'name': 'ham and mushrooms', 'size': 'S', 'price': 9},
    {'type': 'classic', 'name': 'ham and mushrooms', 'size': 'M', 'price': 11},
    {'type': 'classic', 'name': 'ham and mushrooms', 'size': 'L', 'price': 13},
    {'type': 'classic', 'name': 'ham and mushrooms', 'size': 'XL', 'price': 16},
    {'type': 'classic', 'name': 'ham and mushrooms', 'size': 'XXL', 'price': 19},
    {'type': 'classic', 'name': 'teriyaki', 'size': 'S', 'price': 10},
    {'type': 'classic', 'name': 'teriyaki', 'size': 'M', 'price': 12},
    {'type': 'classic', 'name': 'teriyaki', 'size': 'L', 'price': 14},
    {'type': 'classic', 'name': 'teriyaki', 'size': 'XL', 'price': 17},
    {'type': 'classic', 'name': 'teriyaki', 'size': 'XXL', 'price': 20},
    {'type': 'classic', 'name': 'salami', 'size': 'S', 'price': 8},
    {'type': 'classic', 'name': 'salami', 'size': 'M', 'price': 10},
    {'type': 'classic', 'name': 'salami', 'size': 'L', 'price': 12},
    {'type': 'classic', 'name': 'salami', 'size': 'XL', 'price': 15},
    {'type': 'classic', 'name': 'salami', 'size': 'XXL', 'price': 18},
    {'type': 'classic', 'name': 'rancho', 'size': 'S', 'price': 9},
    {'type': 'classic', 'name': 'rancho', 'size': 'M', 'price': 11},
    {'type': 'classic', 'name': 'rancho', 'size': 'L', 'price': 13},
    {'type': 'classic', 'name': 'rancho', 'size': 'XL', 'price': 16},
    {'type': 'classic', 'name': 'rancho', 'size': 'XXL', 'price': 19},
    {'type': 'classic', 'name': 'mexicana', 'size': 'S', 'price': 10},
    {'type': 'classic', 'name': 'mexicana', 'size': 'M', 'price': 12},
    {'type': 'classic', 'name': 'mexicana', 'size': 'L', 'price': 14},
    {'type': 'classic', 'name': 'mexicana', 'size': 'XL', 'price': 17},
    {'type': 'classic', 'name': 'mexicana', 'size': 'XXL', 'price': 20},
    {'type': 'veggie', 'name': 'four cheese', 'size': 'S', 'price': 9},
    {'type': 'veggie', 'name': 'four cheese', 'size': 'M', 'price': 11},
    {'type': 'veggie', 'name': 'four cheese', 'size': 'L', 'price': 13},
    {'type': 'veggie', 'name': 'four cheese', 'size': 'XL', 'price': 16},
    {'type': 'veggie', 'name': 'four cheese', 'size': 'XXL', 'price': 19},
    {'type': 'veggie', 'name': 'margarita', 'size': 'S', 'price': 8},
    {'type': 'veggie', 'name': 'margarita', 'size': 'M', 'price': 10},
    {'type': 'veggie', 'name': 'margarita', 'size': 'L', 'price': 12},
    {'type': 'veggie', 'name': 'margarita', 'size': 'XL', 'price': 15},
    {'type': 'veggie', 'name': 'margarita', 'size': 'XXL', 'price': 18},
    {'type': 'veggie', 'name': 'teriyaki', 'size': 'S', 'price': 10},
    {'type': 'veggie', 'name': 'teriyaki', 'size': 'M', 'price': 12},
    {'type': 'veggie', 'name': 'teriyaki', 'size': 'L', 'price': 14},
    {'type': 'veggie', 'name': 'teriyaki', 'size': 'XL', 'price': 17},
    {'type': 'veggie', 'name': 'teriyaki', 'size': 'XXL', 'price': 20},
    {'type': 'veggie', 'name': 'mushroom', 'size': 'S', 'price': 9},
    {'type': 'veggie', 'name': 'mushroom', 'size': 'M', 'price': 11},
    {'type': 'veggie', 'name': 'mushroom', 'size': 'L', 'price': 13},
    {'type': 'veggie', 'name': 'mushroom', 'size': 'XL', 'price': 16},
    {'type': 'veggie', 'name': 'mushroom', 'size': 'XXL', 'price': 19},
    {'type': 'veggie', 'name': 'jalapeno', 'size': 'S', 'price': 8},
    {'type': 'veggie', 'name': 'jalapeno', 'size': 'M', 'price': 10},
    {'type': 'veggie', 'name': 'jalapeno', 'size': 'L', 'price': 12},
    {'type': 'veggie', 'name': 'jalapeno', 'size': 'XL', 'price': 15},
    {'type': 'veggie', 'name': 'jalapeno', 'size': 'XXL', 'price': 18},
    {'type': 'veggie', 'name': 'rancho', 'size': 'S', 'price': 9},
    {'type': 'veggie', 'name': 'rancho', 'size': 'M', 'price': 11},
    {'type': 'veggie', 'name': 'rancho', 'size': 'L', 'price': 13},
    {'type': 'veggie', 'name': 'rancho', 'size': 'XL', 'price': 16},
    {'type': 'veggie', 'name': 'rancho', 'size': 'XXL', 'price': 19},
    {'type': 'veggie', 'name': 'mexicana', 'size': 'S', 'price': 10},
    {'type': 'veggie', 'name': 'mexicana', 'size': 'M', 'price': 12},
    {'type': 'veggie', 'name': 'mexicana', 'size': 'L', 'price': 14},
    {'type': 'veggie', 'name': 'mexicana', 'size': 'XL', 'price': 17},
    {'type': 'veggie', 'name': 'mexicana', 'size': 'XXL', 'price': 20}
]
